### ISSUE TITLE
help with creating octree from pcl point clouds

### ISSUE THREAD

**Issue by Karthik777** [griegler/octnet#1]
Hi,
I'm trying to create octrees with pcl organised point clouds. What I'm stuck with is what does the ranges and number of ranges mean in the octree_create_from_dense_cpu mean in terms of point clouds and how I procure those from a raw point cloud. If possible. Could you post a code example on how to convert raw pcl pointclouds to octrees.

**Comment by griegler** [comment]
Hi,
`octree_create_from_dense_cpu` is meant for converting dense voxel grids into grid-octree structures. You can use `octree_create_from_pc_cpu` to convert a 3D point cloud with associated feature vectors to a grid-octree.
Here some sample code in Python.

```python
# create oc from voxel grid
dense = np.zeros((vx_res,vx_res,vx_res), dtype=np.float32)
dense[:,0,1:vx_res-1] = 1
dense[:,vx_res-1,1:vx_res-1] = 1
dense[:,:,1] = 1
dense[:,:,vx_res-2] = 1
val_range = np.array([(0.9, 1.1)], dtype=np.float32)
oc_from_dense1 = pyoctnet.Octree.create_from_dense(dense, val_range, n_threads=n_threads)
oc_from_dense2 = pyoctnet.Octree.create_from_dense2(dense, dense[np.newaxis,...], n_threads=n_threads)

# create from point cloud
xyz = np.random.normal(0, 1, (100, 3)).astype(np.float32)
features = np.ones_like(xyz)
oc_from_pcl = pyoctnet.Octree.create_from_pc(xyz, features, vx_res,vx_res,vx_res, normalize=True, n_threads=n_threads)

for idx in range(3):
  xyz[...,idx] = (xyz[...,idx] - xyz[...,idx].min()) / (xyz[...,idx].max() - xyz[...,idx].min())
  xyz[...,idx] *= vx_res
oc_from_pcl = pyoctnet.Octree.create_from_pc(xyz, features, vx_res,vx_res,vx_res, normalize=False, n_threads=n_threads)
```

**Comment by Karthik777** [comment]
This could be a dumb question. But 
the octree method requires a pointcloud normal and a feaure set right. the feature set generated for normal estimation is through radius search or k nearest neighbours. so, how do i get a matrix of the same size as the pointcloud normal?

**Comment by griegler** [comment]
The `create_from_pc` does not require any normals, just the xyz coordinates and a corresponding set of feature vectors for each 3D point. The features can be normal vectors, or height above ground, or whatever you think might be useful in your application. In the simplest case it is just a value different from 0 for each point.
I updated the example code and added a visualization, I hope that clarifies some things.
