### ISSUE TITLE
Unable to execute the training example

### ISSUE THREAD

**Issue by siddharthsrivastava** [griegler/octnet#2]
Hi 

I have successfully compiled the octnet code on my machine. However, while executing the examples, specifically while executing this script

> th train_mn10_r64.lua

, I receive the following error

> /home/siddharth/.luarocks/share/lua/5.1/hdf5/init.lua:15 Unable to find the HDF5 lib we were built against - trying to find it elsewhere	
> /home/siddharth/torch/install/bin/luajit: /home/siddharth/torch/install/share/lua/5.1/trepl/init.lua:389: /home/siddharth/.luarocks/share/lua/5.1/hdf5/ffi.lua:29: libhdf5.so: cannot open shared object file: No such file or directory
> stack traceback:
> 	[C]: in function 'error'
> 	/home/siddharth/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
> 	../common.lua:3: in main chunk
> 	[C]: in function 'dofile'
> 	classification_common.lua:1: in main chunk
> 	[C]: in function 'dofile'
> 	train_mn10_r64.lua:3: in main chunk
> 	[C]: in function 'dofile'
> 	...arth/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
> 	[C]: at 0x00405d50
> 

Does the code have any specific dependency ?

**Comment by griegler** [comment]
Hi,
It seems that you hdf5 is not working in your lua/torch installation. You can look at [this repo](https://github.com/deepmind/torch-hdf5).
However, it should also be ok to remove line 3 in common.lua, as it is never used in the example scripts. I will push an update soon.
