### ISSUE TITLE
Issue with resolution and batch size

### ISSUE THREAD

**Issue by Tetragramm** [griegler/octnet#8]
Increasing resolution obviously requires more memory.  Using example 01 at 128^3 requires more memory than my GPU has.  To try and reduce the memory footprint, I tried to reduce the batch size.

Testing at 64^3 shows that increasing the batch size causes out of memory errors, so reducing it should help.

However, setting the batch size to 16 causes an error "mismatch between the batch size of input (128) and that of target (16)". The first number varies with the batch size (size=12 is 96, ect).  Unfortunately, tracing the callstack back out I see no place that the number would come from.

```
/home/tetragramm/torch/install/share/lua/5.1/nn/THNN.lua:110: bad argument #2 to 'v' (mismatch between the batch size of input (96) and that of target (12) at /home/tetragramm/torch/extra/cunn/lib/THCUNN/generic/ClassNLLCriterion.cu:39)
stack traceback:
	[C]: in function 'v'
	/home/tetragramm/torch/install/share/lua/5.1/nn/THNN.lua:110: in function 'ClassNLLCriterion_updateOutput'
	...amm/torch/install/share/lua/5.1/nn/ClassNLLCriterion.lua:44: in function 'updateOutput'
	...torch/install/share/lua/5.1/nn/CrossEntropyCriterion.lua:20: in function 'forward'
	../common.lua:170: in function 'opfunc'
	/home/tetragramm/torch/install/share/lua/5.1/optim/adam.lua:37: in function 'optimizer'
	../common.lua:180: in function 'train_epoch'
	../common.lua:249: in function 'worker'
	classification_common.lua:97: in function 'classification_worker'
	train_mn10_r64.lua:66: in main chunk
	[C]: in function 'dofile'
```

**Comment by griegler** [comment]
~~The problem is most likely https://github.com/griegler/octnet/blob/master/example/01_classification_modelnet/train_mn10_r64.lua#L58. It should read `:add( nn.Linear(opt.batch_size*8*8*8, 512) )`.~~
No, that was too quick. I will have a more detailed look at it tomorrow morning.

**Comment by griegler** [comment]
Ok, the issue is related to `nn.View`. If you increase the input resolution, your output will also have higher resolution and then the reshape happening in `nn.View` does not fit the batch size. 
So you have two possibilities: You can change the output resolution `8*8*8` in `nn.View` and in the `nn.Linear` that follows, or you add additional pooling layers.
